[[redirects]]
  from = "/transcript/*"
  to = "/transcript/:splat"
  status = 200
  force = true

# Опционально: если хочешь, чтобы все пути вели к существующим файлам
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
